# Generated by Django 5.1.3 on 2025-02-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookExchange', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
