# Generated by Django 5.1.3 on 2025-02-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookExchange', '0002_delete_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LentBooks',
            new_name='CanLend',
        ),
        migrations.RenameModel(
            old_name='BorrowedBooks',
            new_name='WillBorrow',
        ),
    ]
