# Generated by Django 5.1.3 on 2025-02-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookExchange', '0004_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
